// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __simple_hh__
#define __simple_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_simple
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_simple
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_simple
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE example

_CORBA_MODULE_BEG

#ifndef __example_mSimple__
#define __example_mSimple__
  class Simple;
  class _objref_Simple;
  class _impl_Simple;
  
  typedef _objref_Simple* Simple_ptr;
  typedef Simple_ptr SimpleRef;

  class Simple_Helper {
  public:
    typedef Simple_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Simple, Simple_Helper> Simple_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Simple,Simple_Helper > Simple_out;

#endif

  // interface Simple
  class Simple {
  public:
    // Declarations for this interface type.
    typedef Simple_ptr _ptr_type;
    typedef Simple_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Simple :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void Display(const char* sText);

    // Constructors
    inline _objref_Simple()  { _PR_setobj(0); }  // nil
    _objref_Simple(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Simple();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Simple(const _objref_Simple&);
    _objref_Simple& operator = (const _objref_Simple&);
    // not implemented

    friend class Simple;
  };

  class _pof_Simple : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Simple() : _OMNI_NS(proxyObjectFactory)(Simple::_PD_repoId) {}
    virtual ~_pof_Simple();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Simple :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Simple();

    virtual void Display(const char* sText) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_example
_CORBA_MODULE_BEG

  class Simple :
    public virtual example::_impl_Simple,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Simple();

    inline ::example::Simple_ptr _this() {
      return (::example::Simple_ptr) _do_this(::example::Simple::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_example
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
example::Simple::_marshalObjRef(::example::Simple_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_simple
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_simple
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_simple
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_simple
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_simple
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_simple
#endif

#endif  // __simple_hh__

